#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Prettier
files=$(git diff --name-only --cached --diff-filter=ACMR)
if [ ! -z "$files" ]; then
  npx prettier --write $files --ignore-unknown
  git add $files
fi

# ESLint
files=$(git diff --name-only --cached --diff-filter=ACMR "*.js" "*.ts" "*.jsx" "*.tsx")
if [ ! -z "$files" ]; then
  npx eslint --quiet --fix --cache --cache-location ".cache/" $files
  git add $files
fi

# Jest
npx lint-staged